---
- name: Check if Shellcheck is installed
  shell: set -euo pipefail && command -v shellcheck >/dev/null 2>&1
  args:
    executable: /bin/bash
  register: shellcheck_installed
  changed_when: shellcheck_installed.rc != 0
  failed_when: false

- name: Download Shellcheck
  get_url:
    url: "https://storage.googleapis.com/shellcheck/shellcheck-{{ shellcheck_version }}.linux.x86_64.tar.xz"
    dest: "/tmp/shellcheck-{{ shellcheck_version }}.linux.x86_64.tar.xz"
    mode: '0644'
  when: shellcheck_installed is changed

- name: Unarchive Shellcheck
  unarchive:
    src: "/tmp/shellcheck-{{ shellcheck_version }}.linux.x86_64.tar.xz"
    dest: /tmp
    extra_opts:
      - --xz
    remote_src: yes
  when: shellcheck_installed is changed

- name: Install Shellcheck
  copy:
    src: "/tmp/shellcheck-{{ shellcheck_version }}/shellcheck"
    dest: /usr/local/bin/shellcheck
    remote_src: yes
    mode: '0755'
  when: shellcheck_installed is changed
